# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `googleapis-common-protos-types` gem.
# Please instead update this file by running `bin/tapioca gem googleapis-common-protos-types`.


# pkg:gem/googleapis-common-protos-types#lib/google/rpc/status_pb.rb:15
module Google; end

# pkg:gem/googleapis-common-protos-types#lib/google/rpc/status_pb.rb:16
module Google::Rpc; end

# pkg:gem/googleapis-common-protos-types#lib/google/rpc/status_pb.rb:17
class Google::Rpc::Status < ::Google::Protobuf::AbstractMessage; end
