# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mission_control-jobs` gem.
# Please instead update this file by running `bin/tapioca gem mission_control-jobs`.


# pkg:gem/mission_control-jobs#lib/active_job/errors/invalid_operation.rb:1
module ActiveJob; end

class ActiveJob::Base; end

# pkg:gem/mission_control-jobs#lib/active_job/errors/invalid_operation.rb:2
module ActiveJob::Errors; end

# pkg:gem/mission_control-jobs#lib/active_job/errors/invalid_operation.rb:3
class ActiveJob::Errors::InvalidOperation < ::StandardError; end

# pkg:gem/mission_control-jobs#lib/active_job/errors/job_not_found_error.rb:3
class ActiveJob::Errors::JobNotFoundError < ::StandardError
  # @return [JobNotFoundError] a new instance of JobNotFoundError
  #
  # pkg:gem/mission_control-jobs#lib/active_job/errors/job_not_found_error.rb:6
  def initialize(job_or_job_id, job_relation); end

  # Returns the value of attribute job_relation.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/errors/job_not_found_error.rb:4
  def job_relation; end
end

# pkg:gem/mission_control-jobs#lib/active_job/errors/query_error.rb:3
class ActiveJob::Errors::QueryError < ::StandardError; end

# TODO: These (or a version of them) should be moved to +ActiveJob::Core+
# and related concerns when upstreamed.
#
# pkg:gem/mission_control-jobs#lib/active_job/executing.rb:3
module ActiveJob::Executing
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::ActiveJob::Executing::ClassMethods

  # pkg:gem/mission_control-jobs#lib/active_job/executing.rb:23
  def discard; end

  # pkg:gem/mission_control-jobs#lib/active_job/executing.rb:27
  def dispatch; end

  # pkg:gem/mission_control-jobs#lib/active_job/executing.rb:19
  def retry; end

  private

  # pkg:gem/mission_control-jobs#lib/active_job/executing.rb:32
  def jobs_relation_for_discarding; end
end

# pkg:gem/mission_control-jobs#lib/active_job/executing.rb:13
module ActiveJob::Executing::ClassMethods
  # pkg:gem/mission_control-jobs#lib/active_job/executing.rb:14
  def queue_adapter; end
end

# Information about a given error when executing a job.
#
# It's attached to failed jobs at +ActiveJob::Base#last_execution_error+.
#
# pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:4
class ActiveJob::ExecutionError < ::Struct
  # Returns the value of attribute backtrace
  #
  # @return [Object] the current value of backtrace
  #
  # pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:4
  def backtrace; end

  # Sets the attribute backtrace
  #
  # @param value [Object] the value to set the attribute backtrace to.
  # @return [Object] the newly set value
  #
  # pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:4
  def backtrace=(_); end

  # Returns the value of attribute error_class
  #
  # @return [Object] the current value of error_class
  #
  # pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:4
  def error_class; end

  # Sets the attribute error_class
  #
  # @param value [Object] the value to set the attribute error_class to.
  # @return [Object] the newly set value
  #
  # pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:4
  def error_class=(_); end

  # Returns the value of attribute message
  #
  # @return [Object] the current value of message
  #
  # pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:4
  def message; end

  # Sets the attribute message
  #
  # @param value [Object] the value to set the attribute message to.
  # @return [Object] the newly set value
  #
  # pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:4
  def message=(_); end

  # pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:5
  def to_s; end

  class << self
    # pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:4
    def [](*_arg0); end

    # pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:4
    def inspect; end

    # pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:4
    def keyword_init?; end

    # pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:4
    def members; end

    # pkg:gem/mission_control-jobs#lib/active_job/execution_error.rb:4
    def new(*_arg0); end
  end
end

# pkg:gem/mission_control-jobs#lib/active_job/failed.rb:1
module ActiveJob::Failed
  extend ::ActiveSupport::Concern
end

# A proxy for managing jobs without having to load the corresponding
# job class.
#
# This is useful for managing jobs without having the job classes
# present in the code base.
#
# pkg:gem/mission_control-jobs#lib/active_job/job_proxy.rb:6
class ActiveJob::JobProxy < ::ActiveJob::Base
  # @return [JobProxy] a new instance of JobProxy
  #
  # pkg:gem/mission_control-jobs#lib/active_job/job_proxy.rb:11
  def initialize(job_data); end

  # pkg:gem/mission_control-jobs#lib/active_job/job_proxy.rb:28
  def blocked?; end

  # pkg:gem/mission_control-jobs#lib/active_job/job_proxy.rb:28
  def failed?; end

  # pkg:gem/mission_control-jobs#lib/active_job/job_proxy.rb:28
  def finished?; end

  # pkg:gem/mission_control-jobs#lib/active_job/job_proxy.rb:28
  def in_progress?; end

  # Returns the value of attribute job_class_name.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/job_proxy.rb:9
  def job_class_name; end

  # pkg:gem/mission_control-jobs#lib/active_job/job_proxy.rb:28
  def pending?; end

  # @raise [UnsupportedError]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/job_proxy.rb:23
  def perform_now; end

  # pkg:gem/mission_control-jobs#lib/active_job/job_proxy.rb:28
  def scheduled?; end

  # pkg:gem/mission_control-jobs#lib/active_job/job_proxy.rb:17
  def serialize; end
end

# pkg:gem/mission_control-jobs#lib/active_job/job_proxy.rb:7
class ActiveJob::JobProxy::UnsupportedError < ::StandardError; end

# A relation of jobs that can be filtered and acted on.
#
# Relations of jobs are normally fetched via +ActiveJob.jobs+
# or through a given queue (+ActiveJob::Queue#jobs+).
#
# This class offers a fluid interface to query a subset of jobs. For
# example:
#
#   queue = ActiveJob.queues[:default]
#   queue.jobs.limit(10).where(job_class_name: "DummyJob").last
#
# Relations are enumerable, so you can use +Enumerable+ methods on them.
# Notice however that using these methods will imply loading all the relation
# in memory, which could introduce performance concerns.
#
# Internally, +ActiveJob+ will always use paginated queries to the underlying
# queue adapter. The page size can be controlled via +config.active_job.default_page_size+
# (1000 by default).
#
# There are additional performance concerns depending on the configured
# adapter. Please check +ActiveJob::Relation#where+, +ActiveJob::Relation#count+.
#
# pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:22
class ActiveJob::JobsRelation
  include ::Enumerable

  # @return [JobsRelation] a new instance of JobsRelation
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:36
  def initialize(queue_adapter: T.unsafe(nil), default_page_size: T.unsafe(nil)); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:31
  def [](*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:74
  def blocked; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:78
  def blocked?; end

  # Returns the number of jobs in the relation.
  #
  # When filtering jobs, if the adapter doesn't support the filter(s)
  # directly, this will load all the jobs in memory to filter them.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:97
  def count; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:29
  def default_page_size; end

  # Discard all the jobs in the relation.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:146
  def discard_all; end

  # Discard the provided job.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:152
  def discard_job(job); end

  # Dispatch the provided job.
  #
  # This operation is only valid for blocked or scheduled jobs. It will
  # raise an error +ActiveJob::Errors::InvalidOperation+ otherwise.
  #
  # @raise [ActiveJob::Errors::InvalidOperation]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:160
  def dispatch_job(job); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:122
  def each(&block); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:108
  def empty?; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:74
  def failed; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:78
  def failed?; end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:214
  def filtering_needed?; end

  # Find a job by id.
  #
  # Returns nil when not found.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:169
  def find_by_id(job_id); end

  # Find a job by id.
  #
  # Raises +ActiveJob::Errors::JobNotFoundError+ when not found.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:176
  def find_by_id!(job_id); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:74
  def finished; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:78
  def finished?; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:193
  def in_batches(of: T.unsafe(nil), order: T.unsafe(nil), &block); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:74
  def in_progress; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:78
  def in_progress?; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:120
  def inspect; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:29
  def job_class_name; end

  # Returns an array of jobs class names in the first +from_first+ jobs.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:181
  def job_class_names(from_first: T.unsafe(nil)); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:31
  def last(*_arg0, **_arg1, &_arg2); end

  # Returns the number of jobs in the relation.
  #
  # When filtering jobs, if the adapter doesn't support the filter(s)
  # directly, this will load all the jobs in memory to filter them.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:105
  def length; end

  # Sets the max number of jobs to fetch in the query.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:89
  def limit(limit); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:29
  def limit_value; end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:210
  def limit_value_provided?; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:32
  def logger(&_arg0); end

  # Sets an offset for the jobs-fetching query. The first position is 0.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:84
  def offset(offset); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:29
  def offset_value; end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:206
  def paginated?; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:74
  def pending; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:78
  def pending?; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:29
  def queue_name; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:29
  def recurring_task_id; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:185
  def reload; end

  # Retry all the jobs in the queue.
  #
  # This operation is only valid for sets of failed jobs. It will
  # raise an error +ActiveJob::Errors::InvalidOperation+ otherwise.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:130
  def retry_all; end

  # Retry the provided job.
  #
  # This operation is only valid for sets of failed jobs. It will
  # raise an error +ActiveJob::Errors::InvalidOperation+ otherwise.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:140
  def retry_job(job); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:31
  def reverse(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:74
  def scheduled; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:78
  def scheduled?; end

  # Returns the number of jobs in the relation.
  #
  # When filtering jobs, if the adapter doesn't support the filter(s)
  # directly, this will load all the jobs in memory to filter them.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:106
  def size; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:29
  def status; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:112
  def to_s; end

  # Returns a +ActiveJob::JobsRelation+ with the configured filtering options.
  #
  # === Options
  #
  # * <tt>:job_class_name</tt> - To only include the jobs of a given class.
  #   Depending on the configured queue adapter, this will perform the
  #   filtering in memory, which could introduce performance concerns
  #   for large sets of jobs.
  # * <tt>:queue_name</tt> - To only include the jobs in the provided queue.
  # * <tt>:worker_id</tt> - To only include the jobs processed by the provided worker.
  # * <tt>:recurring_task_id</tt> - To only include the jobs corresponding to runs of a recurring task.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:54
  def where(job_class_name: T.unsafe(nil), queue_name: T.unsafe(nil), worker_id: T.unsafe(nil), recurring_task_id: T.unsafe(nil)); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:65
  def with_status(status); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:29
  def worker_id; end

  private

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:227
  def clone_with(**properties); end

  # @raise [ActiveJob::Errors::InvalidOperation]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:280
  def ensure_failed_status; end

  # Filtering for not natively supported filters is performed in memory
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:268
  def filter(jobs); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:276
  def filters; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:288
  def in_ascending_batches(of:); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:300
  def in_descending_batches(of:); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:220
  def job_class_name=(_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:220
  def limit_value=(_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:239
  def load_jobs; end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:263
  def loaded?; end

  # Returns the value of attribute loaded_jobs.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:219
  def loaded_jobs; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:220
  def offset_value=(_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:247
  def perform_each; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:235
  def query_count; end

  # Returns the value of attribute queue_adapter.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:219
  def queue_adapter; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:220
  def queue_name=(_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:220
  def recurring_task_id=(_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:272
  def satisfy_filter?(job); end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:222
  def set_defaults; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:220
  def status=(_arg0); end

  # @raise [ActiveJob::Errors::InvalidOperation]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:284
  def validate_looping_in_batches_is_possible; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:313
  def wait_batch_delay; end

  # pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:220
  def worker_id=(_arg0); end
end

# When no limit value it defaults to "all jobs"
#
# pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:34
ActiveJob::JobsRelation::ALL_JOBS_LIMIT = T.let(T.unsafe(nil), Integer)

# pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:26
ActiveJob::JobsRelation::FILTERS = T.let(T.unsafe(nil), Array)

# pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:28
ActiveJob::JobsRelation::PROPERTIES = T.let(T.unsafe(nil), Array)

# pkg:gem/mission_control-jobs#lib/active_job/jobs_relation.rb:25
ActiveJob::JobsRelation::STATUSES = T.let(T.unsafe(nil), Array)

# pkg:gem/mission_control-jobs#lib/active_job/querying.rb:1
module ActiveJob::Querying
  extend ::ActiveSupport::Concern
  include GeneratedInstanceMethods

  mixes_in_class_methods GeneratedClassMethods
  mixes_in_class_methods ::ActiveJob::Querying::ClassMethods

  # pkg:gem/mission_control-jobs#lib/active_job/querying.rb:30
  def queue; end

  module GeneratedClassMethods
    def default_page_size; end
    def default_page_size=(value); end
    def default_page_size?; end
  end

  module GeneratedInstanceMethods
    def default_page_size; end
    def default_page_size=(value); end
    def default_page_size?; end
  end
end

# pkg:gem/mission_control-jobs#lib/active_job/querying.rb:10
module ActiveJob::Querying::ClassMethods
  # pkg:gem/mission_control-jobs#lib/active_job/querying.rb:18
  def jobs; end

  # pkg:gem/mission_control-jobs#lib/active_job/querying.rb:14
  def queues; end

  private

  # pkg:gem/mission_control-jobs#lib/active_job/querying.rb:23
  def fetch_queues; end
end

# Top-level query methods added to `ActiveJob`
#
# pkg:gem/mission_control-jobs#lib/active_job/querying.rb:35
module ActiveJob::Querying::Root
  # pkg:gem/mission_control-jobs#lib/active_job/querying.rb:40
  def jobs; end

  # pkg:gem/mission_control-jobs#lib/active_job/querying.rb:36
  def queues; end
end

# A queue of jobs
#
# pkg:gem/mission_control-jobs#lib/active_job/queue.rb:2
class ActiveJob::Queue
  # @return [Queue] a new instance of Queue
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:5
  def initialize(name, size: T.unsafe(nil), active: T.unsafe(nil), queue_adapter: T.unsafe(nil)); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:39
  def active?; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:19
  def clear; end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:23
  def empty?; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:54
  def id; end

  # Return an +ActiveJob::JobsRelation+ with the pending jobs in the queue.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:45
  def jobs; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:17
  def length; end

  # Returns the value of attribute name.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:3
  def name; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:27
  def pause; end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:35
  def paused?; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:49
  def reload; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:31
  def resume; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:13
  def size; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:58
  def to_param; end

  private

  # Returns the value of attribute queue_adapter.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue.rb:61
  def queue_adapter; end
end

# pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:1
module ActiveJob::QueueAdapters::AsyncExt
  include ::MissionControl::Jobs::Adapter

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:21
  def clear_queue(*_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:38
  def discard_all_jobs(*_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:41
  def discard_job(*_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:44
  def dispatch_job(*_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:28
  def fetch_jobs(*_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:47
  def find_job(*_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:24
  def jobs_count(*_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:17
  def queue_size(*_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:13
  def queues; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:32
  def retry_all_jobs(*_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:35
  def retry_job(job, *_arg1); end

  # List of filters supported natively. Non-supported filters are done in memory.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:5
  def supported_job_filters(jobs_relation); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/async_ext.rb:9
  def supports_queue_pausing?; end
end

# pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:1
module ActiveJob::QueueAdapters::ResqueExt
  include ::MissionControl::Jobs::Adapter

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:4
  def initialize(redis = T.unsafe(nil)); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:9
  def activating(&block); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:34
  def clear_queue(queue_name); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:72
  def discard_all_jobs(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:76
  def discard_job(job, jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:60
  def fetch_jobs(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:80
  def find_job(job_id, jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:56
  def jobs_count(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:38
  def pause_queue(queue_name); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:46
  def queue_paused?(queue_name); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:30
  def queue_size(queue_name); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:13
  def queues; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:42
  def resume_queue(queue_name); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:64
  def retry_all_jobs(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:68
  def retry_job(job, jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:50
  def supported_job_filters(jobs_relation); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:84
  def supports_queue_pausing?; end

  private

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:91
  def queue_names; end

  # Returns the value of attribute redis.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:89
  def redis; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:95
  def resque_jobs_for(jobs_relation); end
end

# pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:99
class ActiveJob::QueueAdapters::ResqueExt::ResqueJobs
  # @return [ResqueJobs] a new instance of ResqueJobs
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:104
  def initialize(jobs_relation, redis:); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:117
  def all; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:109
  def count; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:102
  def default_page_size(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:142
  def discard(job); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:134
  def discard_all; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:151
  def find_job(job_id); end

  # Returns the value of attribute jobs_relation.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:100
  def jobs_relation; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:102
  def limit_value_provided?(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:102
  def paginated?(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:121
  def retry_all; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:129
  def retry_job(job); end

  private

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:233
  def clear_failed_queue; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:225
  def count_fetched_jobs; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:187
  def deserialize_resque_job(resque_job_hash, index); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:207
  def direct_jobs_count; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:288
  def discard_all_in_batches; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:274
  def discard_all_one_by_one; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:282
  def discard_jobs(jobs); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:198
  def execution_error_from_resque_job(resque_job_hash); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:221
  def failed_jobs_count; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:176
  def fetch_failed_resque_jobs; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:180
  def fetch_queue_resque_jobs; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:168
  def fetch_resque_jobs; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:296
  def handle_resque_job_error(job, error); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:243
  def in_transactional_jobs_batches(jobs); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:292
  def jobs_by_id; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:211
  def pending_jobs_count; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:229
  def queue_redis_key; end

  # Returns the value of attribute redis.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:156
  def redis; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:264
  def requeue(job); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:259
  def resque_requeue_and_discard(job); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:255
  def retry_all_in_batches; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:237
  def retry_jobs(jobs); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:164
  def targeting_all_jobs?; end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:251
  def use_batches?; end
end

# Redis transactions severely speed up operations, specially when the network latency is high.
# We limit the transaction size because large batches can result in redis timeout errors.
#
# pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:162
ActiveJob::QueueAdapters::ResqueExt::ResqueJobs::MAX_REDIS_TRANSACTION_SIZE = T.let(T.unsafe(nil), Integer)

# See +Resque::Datastore#remove_from_failed_queue+
#
# pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/resque_ext.rb:158
ActiveJob::QueueAdapters::ResqueExt::ResqueJobs::SENTINEL = T.let(T.unsafe(nil), String)

# pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:1
module ActiveJob::QueueAdapters::SolidQueueExt
  include ::MissionControl::Jobs::Adapter
  include ::ActiveJob::QueueAdapters::SolidQueueExt::Workers
  include ::ActiveJob::QueueAdapters::SolidQueueExt::RecurringTasks

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:22
  def clear_queue(queue_name); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:64
  def discard_all_jobs(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:68
  def discard_job(job, jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:72
  def dispatch_job(job, jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:50
  def fetch_jobs(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:76
  def find_job(job_id, *_arg1); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:46
  def jobs_count(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:26
  def pause_queue(queue_name); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:34
  def queue_paused?(queue_name); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:18
  def queue_size(queue_name); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:5
  def queues; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:30
  def resume_queue(queue_name); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:56
  def retry_all_jobs(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:60
  def retry_job(job, jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:42
  def supported_job_filters(*_arg0); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:38
  def supported_job_statuses; end

  private

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:95
  def deserialize_and_proxy_solid_queue_job(solid_queue_job, job_status = T.unsafe(nil)); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:125
  def dispatch_immediately(job); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:116
  def execution_error_from_solid_queue_job(solid_queue_job); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:83
  def find_queue_by_name(queue_name); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:91
  def find_solid_queue_job(job_id, jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:87
  def find_solid_queue_job!(job_id, jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:112
  def status_from_solid_queue_job(solid_queue_job); end
end

# pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/recurring_tasks.rb:1
module ActiveJob::QueueAdapters::SolidQueueExt::RecurringTasks
  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/recurring_tasks.rb:29
  def can_enqueue_recurring_task?(task_id); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/recurring_tasks.rb:23
  def enqueue_recurring_task(task_id); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/recurring_tasks.rb:16
  def find_recurring_task(task_id); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/recurring_tasks.rb:6
  def recurring_tasks; end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/recurring_tasks.rb:2
  def supports_recurring_tasks?; end

  private

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/recurring_tasks.rb:36
  def recurring_task_attributes_from_solid_queue_recurring_task(task); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/recurring_tasks.rb:49
  def recurring_task_last_enqueued_at(task_keys); end
end

# pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:136
class ActiveJob::QueueAdapters::SolidQueueExt::SolidQueueJobs
  # @return [SolidQueueJobs] a new instance of SolidQueueJobs
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:146
  def initialize(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:154
  def count; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:175
  def default_page_size(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:164
  def discard_all; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:158
  def find_job(active_job_id); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:175
  def job_class_name(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:150
  def jobs; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:175
  def limit_value(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:175
  def limit_value_provided?(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:175
  def offset_value(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:175
  def queue_name(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:175
  def recurring_task_id(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:168
  def retry_all; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:175
  def worker_id(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:214
  def direct_count; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:224
  def execution_class_by_status; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:178
  def executions; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:252
  def filter_executions_by_class(executions); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:256
  def filter_executions_by_process_id(executions); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:238
  def filter_executions_by_queue(executions); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:266
  def filter_executions_by_task_key(executions); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:270
  def filter_jobs_by_class(jobs); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:248
  def filter_jobs_by_queue(jobs); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:189
  def finished_jobs; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:234
  def include_execution_association(executions); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:218
  def internally_limited_count; end

  # Returns the value of attribute jobs_relation.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:173
  def jobs_relation; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:274
  def limit(executions_or_jobs); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:286
  def matches_queue_name?(job); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:210
  def matches_relation_filters?(job); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:282
  def matches_status?(job); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:278
  def offset(executions_or_jobs); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:201
  def order_executions(executions); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:197
  def order_finished_jobs(jobs); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:290
  def solid_queue_status; end
end

# pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext.rb:137
ActiveJob::QueueAdapters::SolidQueueExt::SolidQueueJobs::STATUS_MAP = T.let(T.unsafe(nil), Hash)

# pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/workers.rb:1
module ActiveJob::QueueAdapters::SolidQueueExt::Workers
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/workers.rb:12
  def count_workers(workers_relation); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/workers.rb:2
  def exposes_workers?; end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/workers.rb:6
  def fetch_workers(workers_relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/workers.rb:16
  def find_worker(worker_id); end

  private

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/workers.rb:23
  def solid_queue_processes_from_workers_relation(relation); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/workers.rb:31
  def worker_attributes_from_solid_queue_process(process); end

  # pkg:gem/mission_control-jobs#lib/active_job/queue_adapters/solid_queue_ext/workers.rb:27
  def worker_from_solid_queue_process(process); end
end

# An enumerable collection of queues that supports direct access to queues by name.
#
#   queue_1 = ApplicationJob::Queue.new("queue_1")
#   queue_2 = ApplicationJob::Queue.new("queue_2")
#   queues = ApplicationJob::Queues.new([queue_1, queue_2])
#
#   queues[:queue_1] #=> queue_1
#   queues[:queue_2] #=> queue_2
#   queues.to_a #=> [ queue_1, queue_2 ] # Enumerable
#
# See +ActiveJob::Queue+.
#
# pkg:gem/mission_control-jobs#lib/active_job/queues.rb:12
class ActiveJob::Queues
  include ::Enumerable

  # @return [Queues] a new instance of Queues
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queues.rb:19
  def initialize(queues); end

  # pkg:gem/mission_control-jobs#lib/active_job/queues.rb:17
  def [](*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queues.rb:15
  def each(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queues.rb:17
  def inspect(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queues.rb:17
  def length(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queues.rb:17
  def size(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/active_job/queues.rb:23
  def to_h; end

  # pkg:gem/mission_control-jobs#lib/active_job/queues.rb:17
  def to_s(*_arg0, **_arg1, &_arg2); end

  private

  # Returns the value of attribute queues_by_name.
  #
  # pkg:gem/mission_control-jobs#lib/active_job/queues.rb:28
  def queues_by_name; end

  # pkg:gem/mission_control-jobs#lib/active_job/queues.rb:16
  def values(*_arg0, **_arg1, &_arg2); end
end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/version.rb:1
module MissionControl; end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/version.rb:2
module MissionControl::Jobs
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:14
  def adapters; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:14
  def adapters=(val); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:15
  def applications; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:15
  def applications=(val); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:23
  def backtrace_cleaner; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:23
  def backtrace_cleaner=(val); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:16
  def base_controller_class; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:16
  def base_controller_class=(val); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:17
  def delay_between_bulk_operation_batches; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:17
  def delay_between_bulk_operation_batches=(val); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:22
  def importmap; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:22
  def importmap=(val); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:19
  def internal_query_count_limit; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:19
  def internal_query_count_limit=(val); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:18
  def logger; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:18
  def logger=(val); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:21
  def scheduled_job_delay_threshold; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:21
  def scheduled_job_delay_threshold=(val); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:20
  def show_console_help; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:20
  def show_console_help=(val); end

  class << self
    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:14
    def adapters; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:14
    def adapters=(val); end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:15
    def applications; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:15
    def applications=(val); end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:23
    def backtrace_cleaner; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:23
    def backtrace_cleaner=(val); end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:16
    def base_controller_class; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:16
    def base_controller_class=(val); end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:17
    def delay_between_bulk_operation_batches; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:17
    def delay_between_bulk_operation_batches=(val); end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:22
    def importmap; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:22
    def importmap=(val); end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:19
    def internal_query_count_limit; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:19
    def internal_query_count_limit=(val); end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:18
    def logger; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:18
    def logger=(val); end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs/engine.rb:8
    def railtie_helpers_paths; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs/engine.rb:8
    def railtie_namespace; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs/engine.rb:8
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:21
    def scheduled_job_delay_threshold; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:21
    def scheduled_job_delay_threshold=(val); end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:20
    def show_console_help; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs.rb:20
    def show_console_help=(val); end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs/engine.rb:8
    def table_name_prefix; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs/engine.rb:8
    def use_relative_model_naming?; end
  end
end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:1
module MissionControl::Jobs::Adapter
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:2
  def activating(&block); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:98
  def clear_queue(queue_name); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:136
  def discard_all_jobs(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:140
  def discard_job(job, jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:144
  def dispatch_job(job, jobs_relation); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:28
  def exposes_workers?; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:124
  def fetch_jobs(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:148
  def find_job(job_id, *_arg1); end

  # Returns a recurring task represented by a hash as indicated above
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:52
  def find_recurring_task(recurring_task_id); end

  # Returns a worker represented by a hash as indicated above
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:76
  def find_worker(worker_id); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:120
  def jobs_count(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:102
  def pause_queue(queue_name); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:114
  def queue_paused?(queue_name); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:94
  def queue_size(queue_name); end

  # Returns an array with the list of queues. Each queue is represented as a hash
  # with these attributes:
  #   {
  #     name: "queue_name",
  #     size: 1,
  #     active: true
  #   }
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:90
  def queues; end

  # Returns an array with the list of recurring tasks. Each task is represented as a hash
  # with these attributes:
  #   {
  #     id: "periodic-job",
  #     job_class_name: "MyJob",
  #     arguments: [ 123, { arg: :value }]
  #     schedule: "every monday at 9 am",
  #     last_enqueued_at: Fri, 26 Jan 2024 20:31:09.652174000 UTC +00:00,
  #   }
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:45
  def recurring_tasks; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:108
  def resume_queue(queue_name); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:128
  def retry_all_jobs(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:132
  def retry_job(job, jobs_relation); end

  # List of filters supported natively. Non-supported filters are done in memory.
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:20
  def supported_job_filters(jobs_relation); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:10
  def supported_job_statuses; end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:15
  def supports_job_filter?(jobs_relation, filter); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:6
  def supports_job_status?(status); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:24
  def supports_queue_pausing?; end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:32
  def supports_recurring_tasks?; end

  # Returns an array with the list of workers. Each worker is represented as a hash
  # with these attributes:
  #   {
  #     id: 123,
  #     name: "worker-name",
  #     hostname: "hey-default-101",
  #     last_heartbeat_at: Fri, 26 Jan 2024 20:31:09.652174000 UTC +00:00,
  #     configuration: { ... }
  #     raw_data: { ... }
  #   }
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:69
  def workers; end

  private

  # @raise [MissionControl::Jobs::Errors::IncompatibleAdapter]
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/adapter.rb:153
  def raise_incompatible_adapter_error_from(method_name); end
end

module MissionControl::Jobs::AdapterFeatures
  extend ::ActiveSupport::Concern

  private

  def queue_pausing_supported?; end
  def recurring_tasks_supported?; end
  def supported_job_statuses; end
  def workers_exposed?; end
end

# An application containing backend jobs servers
#
# pkg:gem/mission_control-jobs#lib/mission_control/jobs/application.rb:2
class MissionControl::Jobs::Application
  include ::MissionControl::Jobs::IdentifiedByName

  # @return [Application] a new instance of Application
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/application.rb:7
  def initialize(name:); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/application.rb:12
  def add_servers(queue_adapters_by_name); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/application.rb:3
  def name; end

  # Returns the value of attribute servers.
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/application.rb:5
  def servers; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/application.rb:3
  def to_s; end
end

module MissionControl::Jobs::ApplicationHelper
  include ::MissionControl::Jobs::InterfaceHelper
  include ::MissionControl::Jobs::NavigationHelper
  include ::MissionControl::Jobs::JobsHelper
  include ::MissionControl::Jobs::DatesHelper
end

class MissionControl::Jobs::ApplicationRecord < ::ActiveRecord::Base
  include ::MissionControl::Jobs::ApplicationRecord::GeneratedAttributeMethods
  include ::MissionControl::Jobs::ApplicationRecord::GeneratedAssociationMethods

  class << self
    private

    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_defined_enums; end
    def __class_attr_defined_enums=(new_value); end
  end
end

module MissionControl::Jobs::ApplicationRecord::GeneratedAssociationMethods; end
module MissionControl::Jobs::ApplicationRecord::GeneratedAttributeMethods; end

module MissionControl::Jobs::ApplicationScoped
  extend ::ActiveSupport::Concern

  private

  def activating_job_server(&block); end
  def find_application; end
  def find_server; end
  def set_application; end
end

# A container to register applications
#
# pkg:gem/mission_control-jobs#lib/mission_control/jobs/applications.rb:2
class MissionControl::Jobs::Applications < ::MissionControl::Jobs::IdentifiedElements
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/applications.rb:3
  def add(name, queue_adapters_by_name = T.unsafe(nil)); end
end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/console/connect_to.rb:3
module MissionControl::Jobs::Console; end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/console/connect_to.rb:4
class MissionControl::Jobs::Console::ConnectTo < ::IRB::Command::Base
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/console/connect_to.rb:8
  def execute(server_locator); end
end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/console/context.rb:1
module MissionControl::Jobs::Console::Context
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/console/context.rb:4
  def evaluate(*_arg0); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/console/context.rb:2
  def jobs_server; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/console/context.rb:2
  def jobs_server=(val); end

  class << self
    # pkg:gem/mission_control-jobs#lib/mission_control/jobs/console/context.rb:2
    def jobs_server; end

    # pkg:gem/mission_control-jobs#lib/mission_control/jobs/console/context.rb:2
    def jobs_server=(val); end
  end
end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/console/jobs_help.rb:4
class MissionControl::Jobs::Console::JobsHelp < ::IRB::Command::Base
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/console/jobs_help.rb:8
  def execute(*_arg0); end
end

class MissionControl::Jobs::Current < ::ActiveSupport::CurrentAttributes
  class << self
    def application; end
    def application=(value); end
    def server; end
    def server=(value); end

    private

    def __class_attr_defaults; end
    def __class_attr_defaults=(new_value); end
  end
end

module MissionControl::Jobs::DatesHelper
  def formatted_time(time); end
end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/engine.rb:7
class MissionControl::Jobs::Engine < ::Rails::Engine; end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/errors/incompatible_adapter.rb:1
class MissionControl::Jobs::Errors::IncompatibleAdapter < ::StandardError; end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/errors/resource_not_found.rb:1
class MissionControl::Jobs::Errors::ResourceNotFound < ::StandardError; end

module MissionControl::Jobs::FailedJobsBulkOperations
  extend ::ActiveSupport::Concern
  include ::MissionControl::Jobs::JobFilters

  private

  def bulk_limited_filtered_failed_jobs; end
end

MissionControl::Jobs::FailedJobsBulkOperations::MAX_NUMBER_OF_JOBS_FOR_BULK_OPERATIONS = T.let(T.unsafe(nil), Integer)

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_by_name.rb:1
module MissionControl::Jobs::IdentifiedByName
  extend ::ActiveSupport::Concern

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_by_name.rb:9
  def initialize(name:); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_by_name.rb:13
  def id; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_by_name.rb:17
  def to_param; end
end

# A collection of elements offering a Hash-like access based on
# their +id+.
#
# pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_elements.rb:3
class MissionControl::Jobs::IdentifiedElements
  include ::Enumerable

  # @return [IdentifiedElements] a new instance of IdentifiedElements
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_elements.rb:9
  def initialize; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_elements.rb:13
  def <<(item); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_elements.rb:6
  def [](*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_elements.rb:7
  def each(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_elements.rb:6
  def empty?(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_elements.rb:7
  def last(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_elements.rb:7
  def length(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_elements.rb:17
  def to_a; end

  private

  # Returns the value of attribute elements.
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/identified_elements.rb:22
  def elements; end
end

module MissionControl::Jobs::InterfaceHelper
  def blank_status_emoji(status); end
  def blank_status_notice(message); end
  def modifier_for_status(status); end
end

module MissionControl::Jobs::JobFilters
  extend ::ActiveSupport::Concern

  private

  def active_filters?; end
  def set_filters; end
end

module MissionControl::Jobs::JobScoped
  extend ::ActiveSupport::Concern

  private

  def jobs_relation; end
  def set_job; end
end

module MissionControl::Jobs::JobsHelper
  def attribute_names_for_job_status(status); end
  def clean_backtrace?; end
  def failed_job_backtrace(job, server); end
  def failed_job_error(job); end
  def job_arguments(job); end
  def job_delayed?(job); end
  def job_title(job); end

  private

  def as_renderable_argument(argument); end
  def as_renderable_array(argument); end
  def as_renderable_hash(argument); end
  def renderable_job_arguments_for(job); end
end

module MissionControl::Jobs::NavigationHelper
  def current_section; end
  def jobs_count_with_status(status); end
  def jobs_filter_param; end
  def navigation(title: T.unsafe(nil), section: T.unsafe(nil)); end
  def navigation_section_for_status(status); end
  def navigation_sections; end
  def page_title; end
  def selectable_applications; end
  def selected_application?(application); end
  def selected_server?(server); end
end

module MissionControl::Jobs::NotFoundRedirections
  extend ::ActiveSupport::Concern

  private

  def best_location_for_job_relation(job_relation); end
  def best_location_for_resource_not_found_error(error); end
end

class MissionControl::Jobs::Page
  def initialize(relation, page: T.unsafe(nil), page_size: T.unsafe(nil)); end

  def empty?; end
  def first?; end
  def index; end
  def last?; end
  def next_index; end
  def page_size; end
  def pages_count; end
  def previous_index; end
  def records; end
  def total_count; end

  private

  def offset; end
end

MissionControl::Jobs::Page::DEFAULT_PAGE_SIZE = T.let(T.unsafe(nil), Integer)

module MissionControl::Jobs::QueueScoped
  extend ::ActiveSupport::Concern

  private

  def set_queue; end
end

class MissionControl::Jobs::RecurringTask
  include ::ActiveModel::Validations
  include ::ActiveSupport::Callbacks
  include ::ActiveModel::Validations::HelperMethods
  include ::ActiveModel::Conversion
  include ::ActiveModel::ForbiddenAttributesProtection
  include ::ActiveModel::AttributeAssignment
  include ::ActiveModel::API
  include ::ActiveModel::Access
  include ::ActiveModel::Model
  extend ::ActiveModel::Validations::ClassMethods
  extend ::ActiveModel::Naming
  extend ::ActiveModel::Callbacks
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker
  extend ::ActiveModel::Translation
  extend ::ActiveModel::Validations::HelperMethods
  extend ::ActiveModel::Conversion::ClassMethods

  def initialize(queue_adapter: T.unsafe(nil), **kwargs); end

  def __callbacks; end
  def _run_validate_callbacks; end
  def _run_validate_callbacks!(&block); end
  def _validate_callbacks; end
  def _validators; end
  def _validators?; end
  def arguments; end
  def arguments=(_arg0); end
  def command; end
  def command=(_arg0); end
  def enqueue; end
  def id; end
  def id=(_arg0); end
  def job_class_name; end
  def job_class_name=(_arg0); end
  def jobs; end
  def last_enqueued_at; end
  def last_enqueued_at=(_arg0); end
  def model_name(&_arg0); end
  def next_time; end
  def next_time=(_arg0); end
  def param_delimiter=(_arg0); end
  def priority; end
  def priority=(_arg0); end
  def queue_name; end
  def queue_name=(_arg0); end
  def runnable?; end
  def schedule; end
  def schedule=(_arg0); end

  private

  def queue_adapter; end

  class << self
    def __callbacks; end
    def __callbacks=(value); end
    def _validate_callbacks; end
    def _validate_callbacks=(value); end
    def _validators; end
    def _validators=(value); end
    def _validators?; end
    def param_delimiter; end
    def param_delimiter=(value); end
    def param_delimiter?; end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_param_delimiter; end
    def __class_attr_param_delimiter=(new_value); end
  end
end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/server.rb:3
class MissionControl::Jobs::Server
  include ::MissionControl::Jobs::IdentifiedByName
  include ::MissionControl::Jobs::Server::Workers
  include ::MissionControl::Jobs::Server::RecurringTasks
  include ::MissionControl::Jobs::Server::Serializable
  extend ::MissionControl::Jobs::Server::Serializable::ClassMethods

  # @return [Server] a new instance of Server
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server.rb:9
  def initialize(name:, queue_adapter:, application:, backtrace_cleaner: T.unsafe(nil)); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server.rb:16
  def activating(&block); end

  # Returns the value of attribute application.
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server.rb:7
  def application; end

  # Returns the value of attribute backtrace_cleaner.
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server.rb:7
  def backtrace_cleaner; end

  # Returns the value of attribute name.
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server.rb:4
  def name; end

  # Returns the value of attribute queue_adapter.
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server.rb:7
  def queue_adapter; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server.rb:24
  def queue_adapter_name; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server.rb:4
  def to_s; end
end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/server/recurring_tasks.rb:1
module MissionControl::Jobs::Server::RecurringTasks
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server/recurring_tasks.rb:8
  def find_recurring_task(task_id); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server/recurring_tasks.rb:2
  def recurring_tasks; end
end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/server/serializable.rb:1
module MissionControl::Jobs::Server::Serializable
  extend ::ActiveSupport::Concern

  mixes_in_class_methods ::MissionControl::Jobs::Server::Serializable::ClassMethods

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server/serializable.rb:20
  def to_global_id; end
end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/server/serializable.rb:4
module MissionControl::Jobs::Server::Serializable::ClassMethods
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server/serializable.rb:10
  def from_global_id(global_id); end
end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/server/workers.rb:1
module MissionControl::Jobs::Server::Workers
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server/workers.rb:6
  def find_worker(worker_id); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/server/workers.rb:2
  def workers_relation; end
end

# pkg:gem/mission_control-jobs#lib/mission_control/jobs/version.rb:3
MissionControl::Jobs::VERSION = T.let(T.unsafe(nil), String)

class MissionControl::Jobs::Worker
  include ::ActiveModel::Validations
  include ::ActiveSupport::Callbacks
  include ::ActiveModel::Validations::HelperMethods
  include ::ActiveModel::Conversion
  include ::ActiveModel::ForbiddenAttributesProtection
  include ::ActiveModel::AttributeAssignment
  include ::ActiveModel::API
  include ::ActiveModel::Access
  include ::ActiveModel::Model
  extend ::ActiveModel::Validations::ClassMethods
  extend ::ActiveModel::Naming
  extend ::ActiveModel::Callbacks
  extend ::ActiveSupport::Callbacks::ClassMethods
  extend ::ActiveSupport::DescendantsTracker
  extend ::ActiveModel::Translation
  extend ::ActiveModel::Validations::HelperMethods
  extend ::ActiveModel::Conversion::ClassMethods

  def initialize(queue_adapter: T.unsafe(nil), **kwargs); end

  def __callbacks; end
  def _run_validate_callbacks; end
  def _run_validate_callbacks!(&block); end
  def _validate_callbacks; end
  def _validators; end
  def _validators?; end
  def configuration; end
  def configuration=(_arg0); end
  def hostname; end
  def hostname=(_arg0); end
  def id; end
  def id=(_arg0); end
  def jobs; end
  def last_heartbeat_at; end
  def last_heartbeat_at=(_arg0); end
  def model_name(&_arg0); end
  def name; end
  def name=(_arg0); end
  def param_delimiter=(_arg0); end
  def raw_data; end
  def raw_data=(_arg0); end

  private

  def queue_adapter; end

  class << self
    def __callbacks; end
    def __callbacks=(value); end
    def _validate_callbacks; end
    def _validate_callbacks=(value); end
    def _validators; end
    def _validators=(value); end
    def _validators?; end
    def param_delimiter; end
    def param_delimiter=(value); end
    def param_delimiter?; end

    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__validators; end
    def __class_attr__validators=(new_value); end
    def __class_attr_param_delimiter; end
    def __class_attr_param_delimiter=(new_value); end
  end
end

# A relation of workers.
#
# Relations are enumerable, so you can use +Enumerable+ methods on them.
# Notice however that using these methods will imply loading all the relation
# in memory, which could introduce performance concerns.
#
# pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:6
class MissionControl::Jobs::WorkersRelation
  include ::Enumerable

  # @return [WorkersRelation] a new instance of WorkersRelation
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:15
  def initialize(queue_adapter:); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:11
  def [](*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:38
  def count; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:29
  def each(&block); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:46
  def empty?; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:11
  def last(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:50
  def length; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:25
  def limit(limit); end

  # Returns the value of attribute limit_value.
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:9
  def limit_value; end

  # Sets the attribute limit_value
  #
  # @param value the value to set the attribute limit_value to.
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:9
  def limit_value=(_arg0); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:21
  def offset(offset); end

  # Returns the value of attribute offset_value.
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:9
  def offset_value; end

  # Sets the attribute offset_value
  #
  # @param value the value to set the attribute offset_value to.
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:9
  def offset_value=(_arg0); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:33
  def reload; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:11
  def reverse(*_arg0, **_arg1, &_arg2); end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:51
  def size; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:11
  def to_s(*_arg0, **_arg1, &_arg2); end

  private

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:71
  def clone_with(**properties); end

  # @return [Boolean]
  #
  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:67
  def loaded?; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:63
  def query_count; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:54
  def set_defaults; end

  # pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:59
  def workers; end
end

# When no limit value it defaults to "all workers"
#
# pkg:gem/mission_control-jobs#lib/mission_control/jobs/workers_relation.rb:13
MissionControl::Jobs::WorkersRelation::ALL_WORKERS_LIMIT = T.let(T.unsafe(nil), Integer)
