# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `okcomputer` gem.
# Please instead update this file by running `bin/tapioca gem okcomputer`.


# Private: Storage of the checks which have been registered with OkComputer.
#
# No one is expected to interact directly with this class, but rather through
# the outer OkComputer interface.
#
# pkg:gem/okcomputer#lib/ok_computer/configuration.rb:1
module OkComputer
  class << self
    # Public: Option to disable third-party app performance tools (.e.g NewRelic) from counting OkComputer routes towards their total.
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:59
    def analytics_ignore; end

    # Public: Option to disable third-party app performance tools (.e.g NewRelic) from counting OkComputer routes towards their total.
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:59
    def analytics_ignore=(_arg0); end

    # Public: Attempt to authenticate against required username and password
    #
    # username - Username to authenticate with
    # password - Password to authenticate with
    #
    # Returns a Boolean
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:28
    def authenticate(username_try, password_try); end

    # Public: whether to execute checks in parallel.
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:56
    def check_in_parallel; end

    # Public: whether to execute checks in parallel.
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:56
    def check_in_parallel=(_arg0); end

    # Public: Logger to use to log check results
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:62
    def logger; end

    # Public: Logger to use to log check results
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:62
    def logger=(_arg0); end

    # Public: Mark listed checks as optional
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:44
    def make_optional(checks); end

    # Public: The route to automatically mount the OkComputer engine. Setting to false
    # prevents OkComputer from automatically mounting itself.
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:53
    def mount_at; end

    # Public: The route to automatically mount the OkComputer engine. Setting to false
    # prevents OkComputer from automatically mounting itself.
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:53
    def mount_at=(_arg0); end

    # Private: The options container
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:71
    def options; end

    # Private: The options container
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:71
    def options=(_arg0); end

    # Private: The password for access to checks
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:68
    def password; end

    # Private: The password for access to checks
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:68
    def password=(_arg0); end

    # pkg:gem/okcomputer#lib/ok_computer/engine.rb:3
    def railtie_helpers_paths; end

    # pkg:gem/okcomputer#lib/ok_computer/engine.rb:3
    def railtie_namespace; end

    # pkg:gem/okcomputer#lib/ok_computer/engine.rb:3
    def railtie_routes_url_helpers(include_path_helpers = T.unsafe(nil)); end

    # Public: Configure HTTP Basic authentication
    #
    # username - Username required to view checks
    # password - Password required to view checks
    # options - Hash of additional options
    #   - except - Array of checks to skip authentication for
    #
    # Examples:
    #
    #     OkComputer.require_authentication("foo", "bar")
    #     # => Require authentication with foo:bar for all checks
    #
    #     OkComputer.require_authentication("foo", "bar", except: %w(default nonsecret))
    #     # => Require authentication with foo:bar for all checks except the checks named "default" and "nonsecret"
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:16
    def require_authentication(username, password, options = T.unsafe(nil)); end

    # Public: Whether OkComputer is configured to require authentication
    #
    # Returns a Boolean
    #
    # @return [Boolean]
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:37
    def requires_authentication?(params = T.unsafe(nil)); end

    # pkg:gem/okcomputer#lib/ok_computer/engine.rb:3
    def table_name_prefix; end

    # pkg:gem/okcomputer#lib/ok_computer/engine.rb:3
    def use_relative_model_naming?; end

    # Private: The username for access to checks
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:65
    def username; end

    # Private: The username for access to checks
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:65
    def username=(_arg0); end

    # # Private: Configure a whitelist of checks to skip authentication
    #
    # pkg:gem/okcomputer#lib/ok_computer/configuration.rb:74
    def whitelist; end
  end
end

# Verifies if the mail server configured for ActionMailer is responding.
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/action_mailer_check.rb:3
class OkComputer::ActionMailerCheck < ::OkComputer::PingCheck
  # @return [ActionMailerCheck] a new instance of ActionMailerCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/action_mailer_check.rb:7
  def initialize(klass = T.unsafe(nil), timeout = T.unsafe(nil)); end

  # Public: Return the status of the check
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/action_mailer_check.rb:16
  def check; end

  # Returns the value of attribute host.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/action_mailer_check.rb:5
  def host; end

  # Sets the attribute host
  #
  # @param value the value to set the attribute host to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/action_mailer_check.rb:5
  def host=(_arg0); end

  # Returns the value of attribute klass.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/action_mailer_check.rb:5
  def klass; end

  # Sets the attribute klass
  #
  # @param value the value to set the attribute klass to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/action_mailer_check.rb:5
  def klass=(_arg0); end

  # Returns the value of attribute port.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/action_mailer_check.rb:5
  def port; end

  # Sets the attribute port
  #
  # @param value the value to set the attribute port to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/action_mailer_check.rb:5
  def port=(_arg0); end

  # Returns the value of attribute timeout.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/action_mailer_check.rb:5
  def timeout; end

  # Sets the attribute timeout
  #
  # @param value the value to set the attribute timeout to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/action_mailer_check.rb:5
  def timeout=(_arg0); end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/active_record_check.rb:2
class OkComputer::ActiveRecordCheck < ::OkComputer::Check
  # Public: Return the schema version of the database
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/active_record_check.rb:4
  def check; end

  # Public: The scema version of the app's database
  #
  # Returns a String with the version number
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/active_record_check.rb:14
  def schema_version; end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/active_record_check.rb:20
class OkComputer::ActiveRecordCheck::ConnectionFailed < ::StandardError; end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/active_record_migrations_check.rb:2
class OkComputer::ActiveRecordMigrationsCheck < ::OkComputer::Check
  # Public: Check if migrations are pending or not
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/active_record_migrations_check.rb:4
  def check; end

  private

  # this check is only valid if config.active_record.migration_error is set to false rather than :page_load
  # :page_load adds a Middleware check that throws an error before the call reaches ok_computer
  # we only run this check when :page_load is set if there are no pending migrations
  # :page_load is the default in development, otherwise this is false
  # see https://github.com/rails/rails/blob/d39db5d1891f7509cde2efc425c9d69bbb77e670/activerecord/lib/active_record/railtie.rb#L103
  #
  # @return [Boolean]
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/active_record_migrations_check.rb:22
  def check_on_page_load?; end

  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/active_record_migrations_check.rb:26
  def error_if_pending_migrations(version_string); end

  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/active_record_migrations_check.rb:34
  def page_load_message; end
end

# Display app version SHA
#
# * If `ENV["SHA"]` is set, uses that value.
# * Otherwise, checks for Capistrano's REVISION file in the app root.
# * Failing these, the check fails
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:7
class OkComputer::AppVersionCheck < ::OkComputer::Check
  # Public: Initialize a check for a backed-up Sidekiq queue
  #
  # file - The path of the version file to check
  # env - The key in ENV to check for a revision SHA
  # transform - The block to optionally transform the version string
  #
  # @return [AppVersionCheck] a new instance of AppVersionCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:17
  def initialize(file: T.unsafe(nil), env: T.unsafe(nil), &transform); end

  # Public: Return the application version
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:24
  def check; end

  # Returns the value of attribute env.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:9
  def env; end

  # Sets the attribute env
  #
  # @param value the value to set the attribute env to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:9
  def env=(_arg0); end

  # Returns the value of attribute file.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:8
  def file; end

  # Sets the attribute file
  #
  # @param value the value to set the attribute file to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:8
  def file=(_arg0); end

  # Returns the value of attribute transform.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:10
  def transform; end

  # Sets the attribute transform
  #
  # @param value the value to set the attribute transform to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:10
  def transform=(_arg0); end

  # Public: The application version
  #
  # Returns a String
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:34
  def version; end

  private

  # Private: Version stored in environment variable
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:41
  def version_from_env; end

  # Private: Version stored in Capistrano revision file
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:46
  def version_from_file; end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/app_version_check.rb:51
class OkComputer::AppVersionCheck::UnknownRevision < ::StandardError; end

# Verifies that the Rails cache is set up and can speak with Memcached
# running on the given host (defaults to local).
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check.rb:4
class OkComputer::CacheCheck < ::OkComputer::Check
  # @return [CacheCheck] a new instance of CacheCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check.rb:7
  def initialize(host = T.unsafe(nil)); end

  # Public: Check whether the cache is active
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check.rb:12
  def check; end

  # Returns the value of attribute host.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check.rb:5
  def host; end

  # Sets the attribute host
  #
  # @param value the value to set the attribute host to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check.rb:5
  def host=(_arg0); end

  # Public: Outputs stats string for cache
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check.rb:20
  def stats; end

  private

  # Private: Convert bytes to megabytes
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check.rb:35
  def to_megabytes(bytes); end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check.rb:39
class OkComputer::CacheCheck::ConnectionFailed < ::StandardError; end

# Verifies that Rails cache is set up and can speak with SolidCache
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check_solid_cache.rb:3
class OkComputer::CacheCheckSolidCache < ::OkComputer::Check
  # Public: Check whether the cache is active
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check_solid_cache.rb:5
  def check; end

  # Public: Outputs stats string for cache
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check_solid_cache.rb:13
  def stats; end

  private

  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check_solid_cache.rb:37
  def format_duration(seconds); end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/cache_check_solid_cache.rb:47
class OkComputer::CacheCheckSolidCache::ConnectionFailed < ::StandardError; end

# pkg:gem/okcomputer#lib/ok_computer/check.rb:4
class OkComputer::Check
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:49
  def <=>(check); end

  # Public: Clear any prior failures
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:77
  def clear; end

  # nil by default, only set to true if the check deems itself failed
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:8
  def failure_occurred; end

  # nil by default, only set to true if the check deems itself failed
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:8
  def failure_occurred=(_arg0); end

  # Public: Mark that this check has failed in some way
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:65
  def mark_failure; end

  # Public: Capture the desired message to display
  #
  # message - Text of the message to display for this check
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:72
  def mark_message(message); end

  # nil by default, set by #check to control the output
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:10
  def message; end

  # nil by default, set by #check to control the output
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:10
  def message=(_arg0); end

  # to be set by Registry upon registration
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:6
  def registrant_name; end

  # to be set by Registry upon registration
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:6
  def registrant_name=(_arg0); end

  # Public: Run the check
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:15
  def run; end

  # Public: Whether the check passed
  #
  # Returns a boolean
  #
  # @return [Boolean]
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:60
  def success?; end

  # Float::NAN by default, set by #run to the elapsed time to run #check
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:12
  def time; end

  # Float::NAN by default, set by #run to the elapsed time to run #check
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:12
  def time=(_arg0); end

  # Public: The JSON output of performing the check
  #
  # Returns a String containing JSON
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:43
  def to_json(*args); end

  # Public: The text output of performing the check
  #
  # Returns a String
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:35
  def to_text; end

  # Private: Benchmark the time it takes to run the block
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:84
  def with_benchmarking; end

  private

  # Private: Perform the appropriate check
  #
  # Your subclass of Check must define its own #check method. This method
  # must return the string to render when performing the check.
  #
  # @raise [CheckNotDefined]
  #
  # pkg:gem/okcomputer#lib/ok_computer/check.rb:27
  def check; end
end

# pkg:gem/okcomputer#lib/ok_computer/check.rb:90
class OkComputer::Check::CheckNotDefined < ::StandardError; end

# pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:2
class OkComputer::CheckCollection
  # Public: Initialize a new CheckCollection
  #
  # display - the display name for the Check Collection
  #
  # @return [CheckCollection] a new instance of CheckCollection
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:8
  def initialize(display); end

  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:43
  def <=>(check); end

  # Public: Returns a  check or collection if it's in the check collection
  #
  # key - a check or collection name
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:31
  def [](key); end

  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:53
  def check_names; end

  # Public: The list of checks in the collection
  #
  # Returns an Array of the collection's values
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:39
  def checks; end

  # Returns the value of attribute collection.
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:3
  def collection; end

  # Sets the attribute collection
  #
  # @param value the value to set the attribute collection to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:3
  def collection=(_arg0); end

  # Public: Deregisters a check from the collection
  #
  # Returns the check
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:78
  def deregister(name); end

  # Returns the value of attribute display.
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:3
  def display; end

  # Sets the attribute display
  #
  # @param value the value to set the attribute display to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:3
  def display=(_arg0); end

  # Public: Returns a check or collection if it's in the check collection
  #
  # key - a check or collection name
  # throws a KeyError when the key is not found
  #
  # @raise [KeyError]
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:22
  def fetch(key, default = T.unsafe(nil)); end

  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:57
  def keys; end

  # Public: Registers a check into the collection
  #
  # Returns the check
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:70
  def register(name, check); end

  # Returns the value of attribute registrant_name.
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:3
  def registrant_name; end

  # Sets the attribute registrant_name
  #
  # @param value the value to set the attribute registrant_name to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:3
  def registrant_name=(_arg0); end

  # Public: Run the collection's checks
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:14
  def run; end

  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:63
  def self_and_sub_collections; end

  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:59
  def sub_collections; end

  # Public: Whether all the checks succeed
  #
  # Returns a Boolean
  #
  # @return [Boolean]
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:105
  def success?; end

  # Public: The JSON of each check in the collection
  #
  # Returns a String containing a JSON array of hashes
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:92
  def to_json(*args); end

  # Public: The text of each check in the collection
  #
  # Returns a String
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:85
  def to_text; end

  # Public: The list of checks in the collection
  #
  # Returns an Array of the collection's values
  #
  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:51
  def values; end

  private

  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:115
  def check_in_parallel; end

  # pkg:gem/okcomputer#lib/ok_computer/check_collection.rb:111
  def check_in_sequence; end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/default_check.rb:2
class OkComputer::DefaultCheck < ::OkComputer::Check
  # Public: Check that Rails can render anything at all
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/default_check.rb:4
  def check; end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:2
class OkComputer::DelayedJobBackedUpCheck < ::OkComputer::SizeThresholdCheck
  # Public: Initialize a check for backed-up Delayed Job jobs
  #
  # priority - Which priority to check for
  # threshold - An Integer to compare the jobs count against to consider it backed up
  # options - Hash of optional parameters
  #    queue - Used to monitor a specific delayed job queue (default: nil)
  #    include_locked - If true, will include currently locked jobs in the query (default: false)
  #    include_errored - If true, will include currently errored jobs in the query (default: false)
  #    greater_than_priority - If true, will include all jobs with a priority value equal or greater than the set value.
  #
  # Example:
  #   check = new(10, 50)
  #   # => The check will look for jobs with priority between
  #   # 0 and 10, considering the jobs as backed up if there
  #   # are more than 50 of them
  #
  # @return [DelayedJobBackedUpCheck] a new instance of DelayedJobBackedUpCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:25
  def initialize(priority, threshold, options = T.unsafe(nil)); end

  # Returns the value of attribute greater_than_priority.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:3
  def greater_than_priority; end

  # Sets the attribute greater_than_priority
  #
  # @param value the value to set the attribute greater_than_priority to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:3
  def greater_than_priority=(_arg0); end

  # Returns the value of attribute include_errored.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:3
  def include_errored; end

  # Sets the attribute include_errored
  #
  # @param value the value to set the attribute include_errored to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:3
  def include_errored=(_arg0); end

  # Returns the value of attribute include_locked.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:3
  def include_locked; end

  # Sets the attribute include_locked
  #
  # @param value the value to set the attribute include_locked to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:3
  def include_locked=(_arg0); end

  # Returns the value of attribute priority.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:3
  def priority; end

  # Sets the attribute priority
  #
  # @param value the value to set the attribute priority to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:3
  def priority=(_arg0); end

  # Returns the value of attribute queue.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:3
  def queue; end

  # Sets the attribute queue
  #
  # @param value the value to set the attribute queue to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:3
  def queue=(_arg0); end

  # Public: How many delayed jobs are pending within the given priority
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:36
  def size; end

  # Returns the value of attribute threshold.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:3
  def threshold; end

  # Sets the attribute threshold
  #
  # @param value the value to set the attribute threshold to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/delayed_job_backed_up_check.rb:3
  def threshold=(_arg0); end
end

# Check if a file system directory exists and has the correct access. This
# may prove useful if the application relies on a mounted shared file system.
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/directory_check.rb:4
class OkComputer::DirectoryCheck < ::OkComputer::Check
  # Public: Initialize a new directory check.
  #
  # directory - the path of the directory.  Can be relative or absolute.
  # writable - true if directory should allow writes;  false if not.
  #
  # @raise [ArgumentError]
  # @return [DirectoryCheck] a new instance of DirectoryCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/directory_check.rb:13
  def initialize(directory, writable = T.unsafe(nil)); end

  # Public: Return the status of the directory check
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/directory_check.rb:21
  def check; end

  # Returns the value of attribute directory.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/directory_check.rb:7
  def directory; end

  # Sets the attribute directory
  #
  # @param value the value to set the attribute directory to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/directory_check.rb:7
  def directory=(_arg0); end

  # Returns the value of attribute writable.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/directory_check.rb:7
  def writable; end

  # Sets the attribute writable
  #
  # @param value the value to set the attribute writable to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/directory_check.rb:7
  def writable=(_arg0); end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/directory_check.rb:5
class OkComputer::DirectoryCheck::ConnectionFailed < ::StandardError; end

# This class performs a health check on an elasticsearch cluster using the
# {cluster health API}[http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/cluster-health.html].
#
# It reports the cluster's name, number of nodes, and status (green, yellow,
# or red). A cluster status of red is reported as a failure, since this means
# one or more primary shards are unavailable. Note that the app may still
# be able to perform some queries on the available indices/shards.
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/elasticsearch_check.rb:9
class OkComputer::ElasticsearchCheck < ::OkComputer::HttpCheck
  # Public: Initialize a new elasticsearch check.
  #
  # host - The hostname of elasticsearch
  # request_timeout - How long to wait to connect before timing out. Defaults to 5 seconds.
  #
  # @return [ElasticsearchCheck] a new instance of ElasticsearchCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/elasticsearch_check.rb:16
  def initialize(host, request_timeout = T.unsafe(nil)); end

  # Public: Return the status of the elasticsearch cluster
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/elasticsearch_check.rb:22
  def check; end

  # Returns a hash from elasticsearch's cluster health API
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/elasticsearch_check.rb:36
  def cluster_health; end

  # Returns the value of attribute host.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/elasticsearch_check.rb:10
  def host; end
end

# pkg:gem/okcomputer#lib/ok_computer/engine.rb:2
class OkComputer::Engine < ::Rails::Engine; end

# Verifies that Rails can write to and read from its cache.
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/generic_cache_check.rb:5
class OkComputer::GenericCacheCheck < ::OkComputer::Check
  # Public: Check whether cache can be written to and read from
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/generic_cache_check.rb:7
  def check; end

  private

  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/generic_cache_check.rb:29
  def cache_key; end

  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/generic_cache_check.rb:33
  def humanize_cache_store_name; end

  # Private: Generate a unique value each time we check
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/generic_cache_check.rb:25
  def test_value; end
end

# Performs a health check by reading a URL over HTTP.
# A successful response is considered passing.
# To implement your own pass/fail criteria, inherit from this
# class, override #check, and call #perform_request to get the
# response body.
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:9
class OkComputer::HttpCheck < ::OkComputer::Check
  # Public: Initialize a new HTTP check.
  #
  # url - The URL to check
  # request_timeout - How long to wait to connect before timing out. Defaults to 5 seconds.
  #
  # @return [HttpCheck] a new instance of HttpCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:18
  def initialize(url, request_timeout = T.unsafe(nil)); end

  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:58
  def basic_auth_options; end

  # Returns the value of attribute basic_auth_password.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:12
  def basic_auth_password; end

  # Sets the attribute basic_auth_password
  #
  # @param value the value to set the attribute basic_auth_password to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:12
  def basic_auth_password=(_arg0); end

  # Returns the value of attribute basic_auth_username.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:12
  def basic_auth_username; end

  # Sets the attribute basic_auth_username
  #
  # @param value the value to set the attribute basic_auth_username to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:12
  def basic_auth_username=(_arg0); end

  # Public: Return the status of the HTTP check
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:24
  def check; end

  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:50
  def parse_url(url); end

  # Public: Actually performs the request against the URL.
  # Returns response body if the request was successful.
  # Otherwise raises a HttpCheck::ConnectionFailed error.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:36
  def perform_request; end

  # Returns the value of attribute request_timeout.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:12
  def request_timeout; end

  # Sets the attribute request_timeout
  #
  # @param value the value to set the attribute request_timeout to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:12
  def request_timeout=(_arg0); end

  # Returns the value of attribute url.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:12
  def url; end

  # Sets the attribute url
  #
  # @param value the value to set the attribute url to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:12
  def url=(_arg0); end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/http_check.rb:10
class OkComputer::HttpCheck::ConnectionFailed < ::StandardError; end

# pkg:gem/okcomputer#lib/ok_computer/legacy_rails_controller_support.rb:2
module OkComputer::LegacyRailsControllerSupport
  # Support 'render plain' for Rails 3
  #
  # pkg:gem/okcomputer#lib/ok_computer/legacy_rails_controller_support.rb:13
  def render(options = T.unsafe(nil), &block); end

  class << self
    # @private
    #
    # pkg:gem/okcomputer#lib/ok_computer/legacy_rails_controller_support.rb:3
    def included(base); end
  end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_check.rb:2
class OkComputer::MongoidCheck < ::OkComputer::Check
  # Public: Initialize a check for a Mongoid replica set
  #
  # session - The name of the Mongoid session to use. Defaults to the
  #   default session.
  #
  # @return [MongoidCheck] a new instance of MongoidCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_check.rb:9
  def initialize(session = T.unsafe(nil)); end

  # Public: Return the status of the mongodb
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_check.rb:20
  def check; end

  # Public: The name of the app's mongodb
  #
  # Returns a string with the mongdb name
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_check.rb:45
  def mongodb_name; end

  # Public: The stats for the app's mongodb
  #
  # Returns a hash with the status of the db
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_check.rb:30
  def mongodb_stats; end

  # Returns the value of attribute session.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_check.rb:3
  def session; end

  # Sets the attribute session
  #
  # @param value the value to set the attribute session to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_check.rb:3
  def session=(_arg0); end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_check.rb:49
class OkComputer::MongoidCheck::ConnectionFailed < ::StandardError; end

# This class provides a check for a mongodb replica set via the Mongoid ORM.
#
# The check first refreshes the cluster status, which communicates with all
# the nodes, discovers any new ones, and figures out which node is the
# primary and which ones are the secondaries. Nodes that are recovering or
# unavailable are automatically removed from rotation. It's okay to do this
# fairly frequently.
#
# The second part of the check attempts to contact the primary node (to
# ensure writes are accepted) and a secondary node (to ensure reads
# can be distributed).
#
# This calls the
# {replSetGetStatus}[http://docs.mongodb.org/manual/reference/command/replSetGetStatus/]
# command on the admin database of each node. This provides further
# information as well as the replica set's name. This could potentially be
# parsed for more actionable information.
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_replica_set_check.rb:19
class OkComputer::MongoidReplicaSetCheck < ::OkComputer::Check
  # Public: Initialize a check for a Mongoid replica set
  #
  # session - The name of the Mongoid session to use. Defaults to the
  #   default session.
  #
  # @return [MongoidReplicaSetCheck] a new instance of MongoidReplicaSetCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_replica_set_check.rb:26
  def initialize(session = T.unsafe(nil)); end

  # Public: Return the status of the mongodb replica set
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_replica_set_check.rb:33
  def check; end

  # Public: The status for the session's mongodb replica set primary
  #
  # Returns a hash with the status of the primary
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_replica_set_check.rb:53
  def primary_status; end

  # Public: Refresh the cluster status
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_replica_set_check.rb:44
  def refresh; end

  # Public: The status for the session's mongodb replica set secondary
  #
  # Returns a hash with the status of the secondary
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_replica_set_check.rb:64
  def secondary_status; end

  # Returns the value of attribute session.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_replica_set_check.rb:20
  def session; end

  # Sets the attribute session
  #
  # @param value the value to set the attribute session to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_replica_set_check.rb:20
  def session=(_arg0); end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/mongoid_replica_set_check.rb:72
class OkComputer::MongoidReplicaSetCheck::ConnectionFailed < ::StandardError; end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/neo4j_check.rb:2
class OkComputer::Neo4jCheck < ::OkComputer::Check
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/neo4j_check.rb:3
  def check; end
end

class OkComputer::OkComputerController < ::ActionController::Base
  def index; end
  def show; end

  private

  def _layout(lookup_context, formats, keys); end
  def _layout_from_proc; end
  def authenticate; end
  def respond(data, status); end
  def status_code(check); end

  class << self
    private

    def __class_attr___callbacks; end
    def __class_attr___callbacks=(new_value); end
    def __class_attr__layout; end
    def __class_attr__layout=(new_value); end
    def __class_attr__layout_conditions; end
    def __class_attr__layout_conditions=(new_value); end
    def __class_attr_config; end
    def __class_attr_config=(new_value); end
    def __class_attr_middleware_stack; end
    def __class_attr_middleware_stack=(new_value); end
    def __class_attr_rescue_handlers; end
    def __class_attr_rescue_handlers=(new_value); end
  end
end

# This check wraps another check and forces it to be successful so as to
# avoid triggering alerts.
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/optional_check.rb:6
class OkComputer::OptionalCheck < ::SimpleDelegator
  # Public: Always successful
  #
  # @return [Boolean]
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/optional_check.rb:8
  def success?; end

  # Public: The text output of performing the check
  #
  # Returns a String
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/optional_check.rb:15
  def to_text; end
end

# Performs a health check by making a TCPSocket request to the host and port.
# A non-error response is considered passing.
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ping_check.rb:4
class OkComputer::PingCheck < ::OkComputer::Check
  # Public: Initialize a new ping check.
  #
  # host - the hostname
  # port - the port, as a string
  # request_timeout - How long to wait to connect before timing out. Defaults to 5 seconds.
  #
  # @raise [ArgumentError]
  # @return [PingCheck] a new instance of PingCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ping_check.rb:14
  def initialize(host, port, request_timeout = T.unsafe(nil)); end

  # Public: Return the status of the Ping check
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ping_check.rb:22
  def check; end

  # Returns the value of attribute host.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ping_check.rb:7
  def host; end

  # Sets the attribute host
  #
  # @param value the value to set the attribute host to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ping_check.rb:7
  def host=(_arg0); end

  # Returns the value of attribute port.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ping_check.rb:7
  def port; end

  # Sets the attribute port
  #
  # @param value the value to set the attribute port to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ping_check.rb:7
  def port=(_arg0); end

  # Returns the value of attribute request_timeout.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ping_check.rb:7
  def request_timeout; end

  # Sets the attribute request_timeout
  #
  # @param value the value to set the attribute request_timeout to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ping_check.rb:7
  def request_timeout=(_arg0); end

  private

  # Returns true if the request was successful.
  # Otherwise raises a PingCheck::ConnectionFailed error.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ping_check.rb:34
  def tcp_socket_request; end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ping_check.rb:5
class OkComputer::PingCheck::ConnectionFailed < ::StandardError; end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/rabbitmq_check.rb:2
class OkComputer::RabbitmqCheck < ::OkComputer::Check
  # @return [RabbitmqCheck] a new instance of RabbitmqCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/rabbitmq_check.rb:5
  def initialize(url = T.unsafe(nil)); end

  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/rabbitmq_check.rb:9
  def check; end

  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/rabbitmq_check.rb:17
  def connection_status; end

  # Returns the value of attribute url.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/rabbitmq_check.rb:3
  def url; end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/rabbitmq_check.rb:27
class OkComputer::RabbitmqCheck::ConnectionFailed < ::StandardError; end

# This class performs a health check on a Redis instance using the
# {INFO command}[http://redis.io/commands/INFO].
#
# It reports the Redis instance's memory usage, uptime, and number of
# connected clients.
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/redis_check.rb:7
class OkComputer::RedisCheck < ::OkComputer::Check
  # Public: Initialize a new Redis check.
  #
  # redis_config - The configuration of the Redis instance.
  #   Expects any valid configuration that can be passed to Redis.new.
  #   See https://github.com/redis/redis-rb#getting-started
  #
  # @return [RedisCheck] a new instance of RedisCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/redis_check.rb:15
  def initialize(redis_config); end

  # Public: Return the status of Redis.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/redis_check.rb:20
  def check; end

  # Returns a redis instance based on configuration
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/redis_check.rb:37
  def redis; end

  # Returns the value of attribute redis_config.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/redis_check.rb:8
  def redis_config; end

  # Returns a hash from Redis's INFO command.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/redis_check.rb:30
  def redis_info; end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/redis_check.rb:41
class OkComputer::RedisCheck::ConnectionFailed < ::StandardError; end

# pkg:gem/okcomputer#lib/ok_computer/registry.rb:6
class OkComputer::Registry
  class << self
    # Public: Return an object containing all the registered checks
    #
    # Returns the default_collection CheckCollection instance
    #
    # pkg:gem/okcomputer#lib/ok_computer/registry.rb:21
    def all; end

    # Public: The default collection of checks
    #
    # Returns @default_collection
    #
    # pkg:gem/okcomputer#lib/ok_computer/registry.rb:33
    def default_collection; end

    # Public: Remove the check of the given name being checked
    #
    # check_name - The name of the check to retrieve
    # collection_name - The name of the check collection the check should be deregistered from
    #
    # pkg:gem/okcomputer#lib/ok_computer/registry.rb:50
    def deregister(check_name, collection_name = T.unsafe(nil)); end

    # Public: Return the check registered to the given name
    #
    # check_name - The name of the check to retrieve
    #
    # Returns the registered check or raises Registry::CheckNotFound
    #
    # pkg:gem/okcomputer#lib/ok_computer/registry.rb:12
    def fetch(name); end

    # Public: Register the given check with OkComputer
    #
    # check_name - The name of the check to retrieve
    # check_object - Instance of Checker to register
    # collection_name - The name of the check collection the check should be registered to
    #
    # pkg:gem/okcomputer#lib/ok_computer/registry.rb:42
    def register(check_name, check_object, collection_name = T.unsafe(nil)); end

    # pkg:gem/okcomputer#lib/ok_computer/registry.rb:28
    def registry; end

    private

    # pkg:gem/okcomputer#lib/ok_computer/registry.rb:54
    def find_collection(collection_name = T.unsafe(nil)); end
  end
end

# used when fetching a check that has not been registered
#
# pkg:gem/okcomputer#lib/ok_computer/registry.rb:62
class OkComputer::Registry::CheckNotFound < ::StandardError; end

# pkg:gem/okcomputer#lib/ok_computer/registry.rb:63
class OkComputer::Registry::CollectionNotFound < ::StandardError; end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_backed_up_check.rb:2
class OkComputer::ResqueBackedUpCheck < ::OkComputer::SizeThresholdCheck
  # Public: Initialize a check for a backed-up Resque queue
  #
  # queue - The name of the Resque queue to check
  # threshold - An Integer to compare the queue's count against to consider
  #   it backed up
  #
  # @return [ResqueBackedUpCheck] a new instance of ResqueBackedUpCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_backed_up_check.rb:11
  def initialize(queue, threshold); end

  # Returns the value of attribute queue.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_backed_up_check.rb:3
  def queue; end

  # Sets the attribute queue
  #
  # @param value the value to set the attribute queue to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_backed_up_check.rb:3
  def queue=(_arg0); end

  # Public: The number of jobs in the check's queue
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_backed_up_check.rb:18
  def size; end

  # Returns the value of attribute threshold.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_backed_up_check.rb:4
  def threshold; end

  # Sets the attribute threshold
  #
  # @param value the value to set the attribute threshold to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_backed_up_check.rb:4
  def threshold=(_arg0); end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_down_check.rb:2
class OkComputer::ResqueDownCheck < ::OkComputer::Check
  # Public: Check whether Resque workers are working
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_down_check.rb:4
  def check; end

  # Public: Whether the given Resque queue has jobs
  #
  # Returns a Boolean
  #
  # @return [Boolean]
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_down_check.rb:16
  def queued?; end

  # Public: Whether the Resque has workers working on a job
  #
  # Returns a Boolean
  #
  # @return [Boolean]
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_down_check.rb:23
  def working?; end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_failure_threshold_check.rb:2
class OkComputer::ResqueFailureThresholdCheck < ::OkComputer::SizeThresholdCheck
  # Public: Initialize a check for a backed-up Resque queue
  #
  # threshold - An Integer to compare the queue's count against to consider
  #   it backed up
  #
  # @return [ResqueFailureThresholdCheck] a new instance of ResqueFailureThresholdCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_failure_threshold_check.rb:9
  def initialize(threshold); end

  # Public: The number of jobs in the check's queue
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_failure_threshold_check.rb:15
  def size; end

  # Returns the value of attribute threshold.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_failure_threshold_check.rb:3
  def threshold; end

  # Sets the attribute threshold
  #
  # @param value the value to set the attribute threshold to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_failure_threshold_check.rb:3
  def threshold=(_arg0); end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_scheduler_check.rb:2
class OkComputer::ResqueSchedulerCheck < ::OkComputer::Check
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_scheduler_check.rb:3
  def check; end

  # @return [Boolean]
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/resque_scheduler_check.rb:12
  def working?; end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ruby_version_check.rb:2
class OkComputer::RubyVersionCheck < ::OkComputer::Check
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/ruby_version_check.rb:3
  def check; end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/sequel_check.rb:2
class OkComputer::SequelCheck < ::OkComputer::Check
  # Public: Initialize the SequelCheck with the database and/or the migration_directory.
  #
  # Defaults to Sequel:Model.db and 'db/migration' respectively. "database" option can be a Proc so that
  # Sequel can be instantiated later in the boot process.
  #
  # @return [SequelCheck] a new instance of SequelCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/sequel_check.rb:9
  def initialize(options = T.unsafe(nil)); end

  # Public: Return the schema version of the database
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/sequel_check.rb:15
  def check; end

  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/sequel_check.rb:22
  def database; end

  # Public: The scema version of the app's database
  #
  # Returns a String with the version number
  #
  # @return [Boolean]
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/sequel_check.rb:29
  def is_current?; end

  # Returns the value of attribute migration_directory.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/sequel_check.rb:3
  def migration_directory; end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/sequel_check.rb:36
class OkComputer::SequelCheck::ConnectionFailed < ::StandardError; end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/sidekiq_latency_check.rb:7
class OkComputer::SidekiqLatencyCheck < ::OkComputer::SizeThresholdCheck
  # Public: Initialize a check for a backed-up Sidekiq queue
  # See https://github.com/mperham/sidekiq/wiki/Monitoring#monitoring-queue-latency
  #
  # queue - The name of the Sidekiq queue to check
  # threshold - An Integer to compare the queue's latency against to consider
  #   it backed up
  #
  # @return [SidekiqLatencyCheck] a new instance of SidekiqLatencyCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/sidekiq_latency_check.rb:16
  def initialize(queue, threshold = T.unsafe(nil)); end

  # Returns the value of attribute queue.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/sidekiq_latency_check.rb:8
  def queue; end

  # Sets the attribute queue
  #
  # @param value the value to set the attribute queue to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/sidekiq_latency_check.rb:8
  def queue=(_arg0); end

  # Public: The latency of the check's queue (in seconds)
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/sidekiq_latency_check.rb:23
  def size; end
end

# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/size_threshold_check.rb:2
class OkComputer::SizeThresholdCheck < ::OkComputer::Check
  # Public: Initialize a check for a backed-up Resque queue
  #
  # name -  the value that this check should be refered to as
  # threshold - An Integer to compare the size object's count against to consider
  #   it backed up
  # size_proc - The block/proc that returns an integer to compare against
  #
  # Examples
  #
  #    SizeThresholdCheck.new("some queue", 2) do
  #      Queue.new("my_queue").size
  #    end
  #
  # @return [SizeThresholdCheck] a new instance of SizeThresholdCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/size_threshold_check.rb:20
  def initialize(name, threshold, &size_proc); end

  # Public: Check whether the given queue is backed up
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/size_threshold_check.rb:27
  def check; end

  # Returns the value of attribute name.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/size_threshold_check.rb:5
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/size_threshold_check.rb:5
  def name=(_arg0); end

  # Public: The number of jobs in the check's queue
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/size_threshold_check.rb:46
  def size; end

  # Returns the value of attribute size_proc.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/size_threshold_check.rb:3
  def size_proc; end

  # Sets the attribute size_proc
  #
  # @param value the value to set the attribute size_proc to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/size_threshold_check.rb:3
  def size_proc=(_arg0); end

  # Returns the value of attribute threshold.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/size_threshold_check.rb:4
  def threshold; end

  # Sets the attribute threshold
  #
  # @param value the value to set the attribute threshold to.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/size_threshold_check.rb:4
  def threshold=(_arg0); end
end

# This class performs a health check on Solr instance using the
# admin/ping handler.
#
# pkg:gem/okcomputer#lib/ok_computer/built_in_checks/solr_check.rb:4
class OkComputer::SolrCheck < ::OkComputer::HttpCheck
  # Public: Initialize a new Solr check.
  #
  # host - The hostname of Solr
  # request_timeout - How long to wait to connect before timing out. Defaults to 5 seconds.
  #
  # @return [SolrCheck] a new instance of SolrCheck
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/solr_check.rb:11
  def initialize(host, request_timeout = T.unsafe(nil)); end

  # Public: Return the status of Solr
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/solr_check.rb:17
  def check; end

  # Returns the value of attribute host.
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/solr_check.rb:5
  def host; end

  # Public: Returns true if Solr's ping returned OK, otherwise false
  #
  # @return [Boolean]
  #
  # pkg:gem/okcomputer#lib/ok_computer/built_in_checks/solr_check.rb:30
  def ping?; end
end
