# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UptimePingJob`.
# Please instead update this file by running `bin/tapioca dsl UptimePingJob`.


class UptimePingJob
  class << self
    sig { params(block: T.nilable(T.proc.params(job: UptimePingJob).void)).returns(T.any(UptimePingJob, FalseClass)) }
    def perform_later(&block); end

    sig { returns(T.untyped) }
    def perform_now; end
  end
end
