# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::V1::BaseController`.
# Please instead update this file by running `bin/tapioca dsl Api::V1::BaseController`.


class Api::V1::BaseController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
