# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Api::V1::PublicController`.
# Please instead update this file by running `bin/tapioca dsl Api::V1::PublicController`.


class Api::V1::PublicController
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
